micronaut:
  application:
    name: test
  security:
    authentication: bearer
    token:
      jwt:
        generator:
          access-token:
            expiration: 3600
          refresh-token:
            secret: eefe82f8-7ca6-11ea-bc55-0242ac130003
        signatures:
          secret:
            generator:
              secret: eefe82f8-7ca6-11ea-bc55-0242ac130003

datasources:
  default:
    url: jdbc:oracle:thin:@localhost:1521/xe
    driverClassName: oracle.jdbc.driver.OracleDriver
    username: test
    password: test
    dialect: org.hibernate.dialect.Oracle10gDialect

jpa:
  default:
    packages-to-scan:
      - 'org.personal.todos'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true